sudo: required

language: node_js
node_js:
  - node

services:
  - docker

before_install:
  # Let's stop postgresql
  - sudo service postgresql stop
  # wait for postgresql to shutdown
  - while sudo lsof -Pi :5432 -sTCP:LISTEN -t; do sleep 1; done
  - docker-compose up -d

script:
  - npm test
